// Copyright 2021 Lightbend Inc.

// Extension for describing entities in general e.g. their associations

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: akkaserverless/component.proto

package akkaserverless

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Options to describe event sourced entities
type EventSourcedEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A mandatory name for the entity - used for type name generation
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A mandatory key name to be used for persisting names with, quite often
	// the name of the entity.
	EntityType string `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	// The associated state message.
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// Zero or more event messages associated with the entity.
	Events []string `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *EventSourcedEntity) Reset() {
	*x = EventSourcedEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akkaserverless_component_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventSourcedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSourcedEntity) ProtoMessage() {}

func (x *EventSourcedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_akkaserverless_component_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSourcedEntity.ProtoReflect.Descriptor instead.
func (*EventSourcedEntity) Descriptor() ([]byte, []int) {
	return file_akkaserverless_component_proto_rawDescGZIP(), []int{0}
}

func (x *EventSourcedEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventSourcedEntity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EventSourcedEntity) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *EventSourcedEntity) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

// Options to describe value entities
type ValueEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A mandatory name for the entity - used for type name generation
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A mandatory key name to be used for persisting names with, quite often
	// the name of the entity.
	EntityType string `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	// The associated state message.
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ValueEntity) Reset() {
	*x = ValueEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akkaserverless_component_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueEntity) ProtoMessage() {}

func (x *ValueEntity) ProtoReflect() protoreflect.Message {
	mi := &file_akkaserverless_component_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueEntity.ProtoReflect.Descriptor instead.
func (*ValueEntity) Descriptor() ([]byte, []int) {
	return file_akkaserverless_component_proto_rawDescGZIP(), []int{1}
}

func (x *ValueEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValueEntity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ValueEntity) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_akkaserverless_component_proto protoreflect.FileDescriptor

var file_akkaserverless_component_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x73, 0x73,
	0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x73, 0x73,
	0x22, 0x77, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x64,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x58, 0x0a, 0x0b, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x42, 0x70, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6b, 0x6b, 0x61, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x73, 0x73, 0x42, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x48, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x62, 0x65, 0x6e,
	0x64, 0x2f, 0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x73, 0x73,
	0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x6c, 0x65, 0x73, 0x73, 0x3b, 0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x6c, 0x65, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_akkaserverless_component_proto_rawDescOnce sync.Once
	file_akkaserverless_component_proto_rawDescData = file_akkaserverless_component_proto_rawDesc
)

func file_akkaserverless_component_proto_rawDescGZIP() []byte {
	file_akkaserverless_component_proto_rawDescOnce.Do(func() {
		file_akkaserverless_component_proto_rawDescData = protoimpl.X.CompressGZIP(file_akkaserverless_component_proto_rawDescData)
	})
	return file_akkaserverless_component_proto_rawDescData
}

var file_akkaserverless_component_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_akkaserverless_component_proto_goTypes = []interface{}{
	(*EventSourcedEntity)(nil), // 0: akkaserverless.EventSourcedEntity
	(*ValueEntity)(nil),        // 1: akkaserverless.ValueEntity
}
var file_akkaserverless_component_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_akkaserverless_component_proto_init() }
func file_akkaserverless_component_proto_init() {
	if File_akkaserverless_component_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_akkaserverless_component_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventSourcedEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akkaserverless_component_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_akkaserverless_component_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_akkaserverless_component_proto_goTypes,
		DependencyIndexes: file_akkaserverless_component_proto_depIdxs,
		MessageInfos:      file_akkaserverless_component_proto_msgTypes,
	}.Build()
	File_akkaserverless_component_proto = out.File
	file_akkaserverless_component_proto_rawDesc = nil
	file_akkaserverless_component_proto_goTypes = nil
	file_akkaserverless_component_proto_depIdxs = nil
}
