// Copyright 2021 Lightbend Inc.

//
// == Akka Serverless TCK model test for views ==
// see tck/src/main/scala/com/akkaserverless/tck/ViewTCK.scala

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: view/view.proto

package view

import (
	_ "github.com/lightbend/akkaserverless-go-sdk/akkaserverless"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
// An `Event` message contains the type of action to take and the state data.
//
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//	*Event_ReturnAsIs
	//	*Event_UppercaseThis
	//	*Event_AppendToExistingState
	//	*Event_Fail
	//	*Event_Ignore
	Event isEvent_Event `protobuf_oneof:"event"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_view_view_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_view_view_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_view_view_proto_rawDescGZIP(), []int{0}
}

func (m *Event) GetEvent() isEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *Event) GetReturnAsIs() *ReturnAsIsEvent {
	if x, ok := x.GetEvent().(*Event_ReturnAsIs); ok {
		return x.ReturnAsIs
	}
	return nil
}

func (x *Event) GetUppercaseThis() *UppercaseThisEvent {
	if x, ok := x.GetEvent().(*Event_UppercaseThis); ok {
		return x.UppercaseThis
	}
	return nil
}

func (x *Event) GetAppendToExistingState() *AppendToExistingState {
	if x, ok := x.GetEvent().(*Event_AppendToExistingState); ok {
		return x.AppendToExistingState
	}
	return nil
}

func (x *Event) GetFail() *FailEvent {
	if x, ok := x.GetEvent().(*Event_Fail); ok {
		return x.Fail
	}
	return nil
}

func (x *Event) GetIgnore() *Ignore {
	if x, ok := x.GetEvent().(*Event_Ignore); ok {
		return x.Ignore
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_ReturnAsIs struct {
	ReturnAsIs *ReturnAsIsEvent `protobuf:"bytes,1,opt,name=return_as_is,json=returnAsIs,proto3,oneof"`
}

type Event_UppercaseThis struct {
	UppercaseThis *UppercaseThisEvent `protobuf:"bytes,2,opt,name=uppercase_this,json=uppercaseThis,proto3,oneof"`
}

type Event_AppendToExistingState struct {
	AppendToExistingState *AppendToExistingState `protobuf:"bytes,3,opt,name=append_to_existing_state,json=appendToExistingState,proto3,oneof"`
}

type Event_Fail struct {
	Fail *FailEvent `protobuf:"bytes,4,opt,name=fail,proto3,oneof"`
}

type Event_Ignore struct {
	Ignore *Ignore `protobuf:"bytes,5,opt,name=ignore,proto3,oneof"`
}

func (*Event_ReturnAsIs) isEvent_Event() {}

func (*Event_UppercaseThis) isEvent_Event() {}

func (*Event_AppendToExistingState) isEvent_Event() {}

func (*Event_Fail) isEvent_Event() {}

func (*Event_Ignore) isEvent_Event() {}

type ReturnAsIsEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReturnAsIsEvent) Reset() {
	*x = ReturnAsIsEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_view_view_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnAsIsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnAsIsEvent) ProtoMessage() {}

func (x *ReturnAsIsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_view_view_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnAsIsEvent.ProtoReflect.Descriptor instead.
func (*ReturnAsIsEvent) Descriptor() ([]byte, []int) {
	return file_view_view_proto_rawDescGZIP(), []int{1}
}

func (x *ReturnAsIsEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type UppercaseThisEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UppercaseThisEvent) Reset() {
	*x = UppercaseThisEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_view_view_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UppercaseThisEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UppercaseThisEvent) ProtoMessage() {}

func (x *UppercaseThisEvent) ProtoReflect() protoreflect.Message {
	mi := &file_view_view_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UppercaseThisEvent.ProtoReflect.Descriptor instead.
func (*UppercaseThisEvent) Descriptor() ([]byte, []int) {
	return file_view_view_proto_rawDescGZIP(), []int{2}
}

func (x *UppercaseThisEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type AppendToExistingState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AppendToExistingState) Reset() {
	*x = AppendToExistingState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_view_view_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendToExistingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendToExistingState) ProtoMessage() {}

func (x *AppendToExistingState) ProtoReflect() protoreflect.Message {
	mi := &file_view_view_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendToExistingState.ProtoReflect.Descriptor instead.
func (*AppendToExistingState) Descriptor() ([]byte, []int) {
	return file_view_view_proto_rawDescGZIP(), []int{3}
}

func (x *AppendToExistingState) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type FailEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FailEvent) Reset() {
	*x = FailEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_view_view_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailEvent) ProtoMessage() {}

func (x *FailEvent) ProtoReflect() protoreflect.Message {
	mi := &file_view_view_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailEvent.ProtoReflect.Descriptor instead.
func (*FailEvent) Descriptor() ([]byte, []int) {
	return file_view_view_proto_rawDescGZIP(), []int{4}
}

type Ignore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ignore) Reset() {
	*x = Ignore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_view_view_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ignore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ignore) ProtoMessage() {}

func (x *Ignore) ProtoReflect() protoreflect.Message {
	mi := &file_view_view_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ignore.ProtoReflect.Descriptor instead.
func (*Ignore) Descriptor() ([]byte, []int) {
	return file_view_view_proto_rawDescGZIP(), []int{5}
}

// The `ViewState` to return after applying an event
type ViewState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ViewState) Reset() {
	*x = ViewState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_view_view_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewState) ProtoMessage() {}

func (x *ViewState) ProtoReflect() protoreflect.Message {
	mi := &file_view_view_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewState.ProtoReflect.Descriptor instead.
func (*ViewState) Descriptor() ([]byte, []int) {
	return file_view_view_proto_rawDescGZIP(), []int{6}
}

func (x *ViewState) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_view_view_proto protoreflect.FileDescriptor

var file_view_view_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x76, 0x69, 0x65, 0x77, 0x2f, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1d, 0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x73,
	0x73, 0x2e, 0x74, 0x63, 0x6b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x77,
	0x1a, 0x20, 0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x73, 0x73,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xb2, 0x03, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x52, 0x0a, 0x0c,
	0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x61, 0x73, 0x5f, 0x69, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c,
	0x65, 0x73, 0x73, 0x2e, 0x74, 0x63, 0x6b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x69,
	0x65, 0x77, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x41, 0x73, 0x49, 0x73, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x41, 0x73, 0x49, 0x73,
	0x12, 0x5a, 0x0a, 0x0e, 0x75, 0x70, 0x70, 0x65, 0x72, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x68,
	0x69, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x61, 0x6b, 0x6b, 0x61, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x74, 0x63, 0x6b, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x55, 0x70, 0x70, 0x65, 0x72, 0x63, 0x61,
	0x73, 0x65, 0x54, 0x68, 0x69, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x75,
	0x70, 0x70, 0x65, 0x72, 0x63, 0x61, 0x73, 0x65, 0x54, 0x68, 0x69, 0x73, 0x12, 0x6f, 0x0a, 0x18,
	0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x6f, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34,
	0x2e, 0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x73, 0x73, 0x2e,
	0x74, 0x63, 0x6b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x41,
	0x70, 0x70, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x15, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x54, 0x6f,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3e, 0x0a,
	0x04, 0x66, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x6b,
	0x6b, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x74, 0x63, 0x6b,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x46, 0x61, 0x69, 0x6c,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x04, 0x66, 0x61, 0x69, 0x6c, 0x12, 0x3f, 0x0a,
	0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x74,
	0x63, 0x6b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x49, 0x67,
	0x6e, 0x6f, 0x72, 0x65, 0x48, 0x00, 0x52, 0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x42, 0x07,
	0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x41, 0x73, 0x49, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x28,
	0x0a, 0x12, 0x55, 0x70, 0x70, 0x65, 0x72, 0x63, 0x61, 0x73, 0x65, 0x54, 0x68, 0x69, 0x73, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2b, 0x0a, 0x15, 0x41, 0x70, 0x70, 0x65,
	0x6e, 0x64, 0x54, 0x6f, 0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0b, 0x0a, 0x09, 0x46, 0x61, 0x69, 0x6c, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x22, 0x08, 0x0a, 0x06, 0x49, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x22, 0x1f, 0x0a, 0x09,
	0x56, 0x69, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xa0, 0x01,
	0x0a, 0x0c, 0x56, 0x69, 0x65, 0x77, 0x54, 0x63, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x8f,
	0x01, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x55, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x24, 0x2e, 0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x74, 0x63, 0x6b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x6b,
	0x6b, 0x61, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x74, 0x63, 0x6b,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x56, 0x69, 0x65, 0x77,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x29, 0xc2, 0x43, 0x11, 0x0a, 0x0f, 0x0a, 0x0d, 0x22, 0x0b,
	0x76, 0x69, 0x65, 0x77, 0x2d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0xc2, 0x43, 0x12, 0x12, 0x10,
	0x0a, 0x0e, 0x0a, 0x0a, 0x76, 0x69, 0x65, 0x77, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x10, 0x01,
	0x32, 0x0f, 0x0a, 0x0d, 0x56, 0x69, 0x65, 0x77, 0x54, 0x63, 0x6b, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x42, 0x58, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x74, 0x63, 0x6b, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x62, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x6b, 0x6b, 0x61, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x6c, 0x65, 0x73, 0x73, 0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x74, 0x63,
	0x6b, 0x2f, 0x76, 0x69, 0x65, 0x77, 0x3b, 0x76, 0x69, 0x65, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_view_view_proto_rawDescOnce sync.Once
	file_view_view_proto_rawDescData = file_view_view_proto_rawDesc
)

func file_view_view_proto_rawDescGZIP() []byte {
	file_view_view_proto_rawDescOnce.Do(func() {
		file_view_view_proto_rawDescData = protoimpl.X.CompressGZIP(file_view_view_proto_rawDescData)
	})
	return file_view_view_proto_rawDescData
}

var file_view_view_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_view_view_proto_goTypes = []interface{}{
	(*Event)(nil),                 // 0: akkaserverless.tck.model.view.Event
	(*ReturnAsIsEvent)(nil),       // 1: akkaserverless.tck.model.view.ReturnAsIsEvent
	(*UppercaseThisEvent)(nil),    // 2: akkaserverless.tck.model.view.UppercaseThisEvent
	(*AppendToExistingState)(nil), // 3: akkaserverless.tck.model.view.AppendToExistingState
	(*FailEvent)(nil),             // 4: akkaserverless.tck.model.view.FailEvent
	(*Ignore)(nil),                // 5: akkaserverless.tck.model.view.Ignore
	(*ViewState)(nil),             // 6: akkaserverless.tck.model.view.ViewState
}
var file_view_view_proto_depIdxs = []int32{
	1, // 0: akkaserverless.tck.model.view.Event.return_as_is:type_name -> akkaserverless.tck.model.view.ReturnAsIsEvent
	2, // 1: akkaserverless.tck.model.view.Event.uppercase_this:type_name -> akkaserverless.tck.model.view.UppercaseThisEvent
	3, // 2: akkaserverless.tck.model.view.Event.append_to_existing_state:type_name -> akkaserverless.tck.model.view.AppendToExistingState
	4, // 3: akkaserverless.tck.model.view.Event.fail:type_name -> akkaserverless.tck.model.view.FailEvent
	5, // 4: akkaserverless.tck.model.view.Event.ignore:type_name -> akkaserverless.tck.model.view.Ignore
	0, // 5: akkaserverless.tck.model.view.ViewTckModel.ProcessUpdateUnary:input_type -> akkaserverless.tck.model.view.Event
	6, // 6: akkaserverless.tck.model.view.ViewTckModel.ProcessUpdateUnary:output_type -> akkaserverless.tck.model.view.ViewState
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_view_view_proto_init() }
func file_view_view_proto_init() {
	if File_view_view_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_view_view_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_view_view_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnAsIsEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_view_view_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UppercaseThisEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_view_view_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendToExistingState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_view_view_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_view_view_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ignore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_view_view_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_view_view_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Event_ReturnAsIs)(nil),
		(*Event_UppercaseThis)(nil),
		(*Event_AppendToExistingState)(nil),
		(*Event_Fail)(nil),
		(*Event_Ignore)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_view_view_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_view_view_proto_goTypes,
		DependencyIndexes: file_view_view_proto_depIdxs,
		MessageInfos:      file_view_view_proto_msgTypes,
	}.Build()
	File_view_view_proto = out.File
	file_view_view_proto_rawDesc = nil
	file_view_view_proto_goTypes = nil
	file_view_view_proto_depIdxs = nil
}
